### PR TITLE
makefile: Update rukpak repository

### PR DESCRIPTION
**Pull request by exdx**
Move off the fork of rukpak to rely on the upstream repository directly

### CODE REVIEW

**Review by timflannagan — COMMENTED** [review]
We need to also remove the replace pin: https://github.com/timflannagan/platform-operators/blob/main/go.mod#L18.

**Comment by exdx** [comment]
> We need to also remove the replace pin: https://github.com/timflannagan/platform-operators/blob/main/go.mod#L18.

Sounds good, I removed the pin and bumped the required version to v0.5.0. Also ran `go mod tidy` afterwards.

**Review by timflannagan — APPROVED** [review]

**Comment by exdx** [comment]
Hmm, looks like something unrelated is failing in CI:
```
 kubectl apply --server-side=true -f https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.21.2/olm.yaml
namespace/olm serverside-applied
namespace/operators serverside-applied
serviceaccount/olm-operator-serviceaccount serverside-applied
clusterrole.rbac.authorization.k8s.io/system:controller:operator-lifecycle-manager serverside-applied
clusterrolebinding.rbac.authorization.k8s.io/olm-operator-binding-olm serverside-applied
deployment.apps/olm-operator serverside-applied
deployment.apps/catalog-operator serverside-applied
clusterrole.rbac.authorization.k8s.io/aggregate-olm-edit serverside-applied
clusterrole.rbac.authorization.k8s.io/aggregate-olm-view serverside-applied
catalogsource.operators.coreos.com/operatorhubio-catalog serverside-applied
unable to recognize "https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.21.2/olm.yaml": no matches for kind "OLMConfig" in version "operators.coreos.com/v1"
unable to recognize "https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.21.2/olm.yaml": no matches for kind "OperatorGroup" in version "operators.coreos.com/v1"
unable to recognize "https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.21.2/olm.yaml": no matches for kind "OperatorGroup" in version "operators.coreos.com/v1"
unable to recognize "https://github.com/operator-framework/operator-lifecycle-manager/releases/download/v0.21.2/olm.yaml": no matches for kind "ClusterServiceVersion" in version "operators.coreos.com/v1alpha1"
```

**Comment by timflannagan** [comment]
#29

**Comment by exdx** [comment]
Hmm, I thought that could be the issue, although it's surprising that it takes any time to have the CRDs be accepted on basically an empty kind cluster. Although maybe due to their size, it makes some sense.

**Pull request merged**
